from django.core.exceptions import ObjectDoesNotExist, ValidationError


def validate_phone():
    pass
